server:
  port: 8080
spring:
  cloud:
    nacos:
      server-addr: 192.168.130.1:8848
      username: nacos
      password: nacos

    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'

  application:
    name: commonservice