server:
  port: 8086

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  cloud:
    nacos:
      server-addr: 192.168.130.1:8848
      username: nacos
      password: nacos

    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: courseservice

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS